rjm_genemu_sandbox_homepage:
    pattern:  /
    defaults: { _controller: RJMGenemuSandboxBundle:Sandbox:index }

rjm_genemu_sandbox_jqueryselect2_entity:
    pattern:  /select2/entity
    defaults: { _controller: RJMGenemuSandboxBundle:Sandbox:select2Entity }
