parameters:
#    rjm_genemu_sandbox.example.class: RJM\Bundle\GenemuSandboxBundle\Example

services:
#    rjm_genemu_sandbox.example:
#        class: %rjm_genemu_sandbox.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
